use serde::{Deserialize, Serialize};

/// Structured feedback posted by agents on task completion.
/// Parsed from YAML blocks in issue comments prefixed with `caloron_feedback:`.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct CaloronFeedback {
    pub task_id: String,
    pub agent_role: String,
    /// 1-10: how clear was the task description?
    pub task_clarity: u8,
    #[serde(default)]
    pub blockers: Vec<String>,
    #[serde(default)]
    pub tools_used: Vec<String>,
    pub tokens_consumed: u64,
    pub time_to_complete_min: u32,
    pub self_assessment: SelfAssessment,
    #[serde(default)]
    pub notes: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum SelfAssessment {
    Completed,
    Partial,
    Blocked,
    Failed,
    /// Synthetic feedback generated by daemon when harness crashes (Addendum H2).
    Crashed,
}

/// Wrapper for the YAML block that appears in comments.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FeedbackComment {
    pub caloron_feedback: CaloronFeedback,
}

impl FeedbackComment {
    /// Try to parse a feedback block from a comment body.
    /// Looks for a YAML block starting with `caloron_feedback:`.
    pub fn parse_from_comment(body: &str) -> Option<CaloronFeedback> {
        // Find the YAML frontmatter block
        let yaml_content = if body.contains("---") {
            // Extract content between --- markers
            let parts: Vec<&str> = body.splitn(3, "---").collect();
            if parts.len() >= 3 {
                parts[1].trim()
            } else {
                return None;
            }
        } else if body.contains("caloron_feedback:") {
            body.trim()
        } else {
            return None;
        };

        if !yaml_content.contains("caloron_feedback:") {
            return None;
        }

        let parsed: FeedbackComment = serde_yaml::from_str(yaml_content).ok()?;
        Some(parsed.caloron_feedback)
    }

    /// Create a synthetic feedback comment for a crashed agent (Addendum H2).
    pub fn synthetic_crash(task_id: &str, agent_role: &str, exit_details: &str) -> CaloronFeedback {
        CaloronFeedback {
            task_id: task_id.to_string(),
            agent_role: agent_role.to_string(),
            task_clarity: 0,
            blockers: vec![format!(
                "Agent process terminated unexpectedly ({exit_details})"
            )],
            tools_used: vec![],
            tokens_consumed: 0,
            time_to_complete_min: 0,
            self_assessment: SelfAssessment::Crashed,
            notes: Some(format!(
                "Synthetic feedback generated by daemon. Process exit: {exit_details}"
            )),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_feedback_from_comment() {
        let comment = r#"---
caloron_feedback:
  task_id: "issue-42"
  agent_role: "backend-developer"
  task_clarity: 4
  blockers:
    - "Error response format was not specified"
  tools_used:
    - "github_mcp"
    - "noether:http_post_json"
  tokens_consumed: 14200
  time_to_complete_min: 47
  self_assessment: "completed"
  notes: "Had to make assumptions about pagination"
---"#;

        let feedback = FeedbackComment::parse_from_comment(comment).unwrap();
        assert_eq!(feedback.task_id, "issue-42");
        assert_eq!(feedback.task_clarity, 4);
        assert_eq!(feedback.blockers.len(), 1);
        assert_eq!(feedback.self_assessment, SelfAssessment::Completed);
        assert_eq!(feedback.tokens_consumed, 14200);
    }

    #[test]
    fn test_parse_no_feedback() {
        let comment = "This is a regular comment with no feedback block.";
        assert!(FeedbackComment::parse_from_comment(comment).is_none());
    }

    #[test]
    fn test_synthetic_crash_feedback() {
        let feedback =
            FeedbackComment::synthetic_crash("issue-42", "backend-developer", "SIGKILL (signal 9)");
        assert_eq!(feedback.self_assessment, SelfAssessment::Crashed);
        assert_eq!(feedback.task_clarity, 0);
        assert_eq!(feedback.tokens_consumed, 0);
        assert!(feedback.blockers[0].contains("SIGKILL"));
    }

    #[test]
    fn test_self_assessment_serialization() {
        assert_eq!(
            serde_json::to_string(&SelfAssessment::Crashed).unwrap(),
            "\"crashed\""
        );
        assert_eq!(
            serde_json::to_string(&SelfAssessment::Completed).unwrap(),
            "\"completed\""
        );
    }
}
